/*
 * ============================================================================
 * CodeGenerator.cpp — DFA → C 词法分析器代码生成
 * ============================================================================
 *
 * 【生成产物】lex.yy.cpp / lex.yy.h
 *
 * 【核心数据结构（生成到 C 源码中）】
 *   nextState[s][c]  — 256 列转移表，-1 无转移
 *   acceptInfo[s]    — 接受态对应的规则 ID，-1 非接受
 *   input_ptr/input_end — 内存缓冲区扫描（set_input 设置）
 *
 * 【yylex 最长匹配算法】
 *   1. state=0，last_accept=-1，last_rule=-1，回退指针 last_pos
 *   2. while 未 EOF：
 *        读字符 c；state = nextState[state][c]
 *        若 state==-1：回退到 last_accept，执行对应规则动作
 *        若 acceptInfo[state]!=-1：记录 last_accept/last_rule/last_pos
 *   3. 无接受则报错
 *   空白规则单独处理：匹配后 continue 不立即返回（Flex 语义）
 *
 * 【execute_action】按 ruleId  switch 嵌入用户 { return T_XXX; } 代码块
 * ============================================================================
 */
#include "CodeGenerator.h"
#include "lex_common.h"
#include <fstream>
#include <iostream>
#include <cstring>
#include <sstream>
using namespace std;

/** 保存 DFA、规则与用户 prologue/epilogue，供 generate 写入磁盘 */
CodeGenerator::CodeGenerator(const vector<DFAState>& dfaStates,
    const vector<Rule>& rules,
    const string& prologue,
    const string& epilogue)
    : states(dfaStates), rules(rules), prologue(prologue), epilogue(epilogue) {}

/**
 * 写出 Flex 兼容的词法器：表驱动 DFA + 回溯式最长匹配（last_accept / last_rule）。
 * 空白规则单独识别，避免在已匹配更长记号后再吞掉尾随空白。
 */
void CodeGenerator::generate(const string& outCpp, const string& outH) {
    ofstream h(outH);
    ofstream cpp(outCpp);
    if (!h || !cpp) { cerr << "Failed to create output files" << endl; exit(1); }

    /* ---------- 生成 lex.yy.h：包含 seulex.h，另声明 yyleng ---------- */
    h << "#ifndef LEX_GENERATED_H\n#define LEX_GENERATED_H\n\n";
    h << "#include \"seulex.h\"\n";
    h << "extern int yyleng;\n";
    h << "#endif\n";

    /* ---------- 生成 lex.yy.cpp 主体 ---------- */
    cpp << "// Generated by SeuLex\n\n";
    cpp << "#include \"lex.yy.h\"\n";
    cpp << "#include \"common_defs.h\"\n";
    cpp << "#include <cstdlib>\n#include <cstdio>\n#include <cstring>\n";
    cpp << "#include <cctype>\n\n";
    cpp << prologue << "\n\n";

    cpp << "static void __attribute__((unused)) yyerror(const char* msg) { "
        << "fprintf(stderr, \"Lexical error: %s at line %d\\\\n\", msg, yylineno); }\n\n";

    cpp << "#ifndef YYTEXT_DEFINED\n";
    cpp << "char* yytext = nullptr;\n";
    cpp << "int yyleng = 0;\n";
    cpp << "int yylineno = 1;\n";
    cpp << "#define YYTEXT_DEFINED\n";
    cpp << "#endif\n\n";
    cpp << "YYSTYPE yylval;\n\n";

    /* DFA 转移表：nextState[state][(unsigned char)c]，-1 表示无转移 */
    cpp << "static const int nextState[" << states.size() << "][256] = {\n";
    for (size_t i = 0; i < states.size(); ++i) {
        cpp << "    { ";
        for (int ch = 0; ch < 256; ++ch) {
            cpp << states[i].next[ch];
            if (ch < 255) cpp << ", ";
        }
        cpp << " }";
        if (i < states.size() - 1) cpp << ",";
        cpp << "\n";
    }
    cpp << "};\n\n";

    /* 各态是否接受及对应 Flex 规则编号（供最长匹配记录 last_rule） */
    cpp << "static const struct { int accept; int ruleId; } acceptInfo[" << states.size() << "] = {\n";
    for (size_t i = 0; i < states.size(); ++i) {
        cpp << "    { " << (states[i].isAccept ? 1 : 0) << ", " << states[i].ruleId << " }";
        if (i < states.size() - 1) cpp << ",";
        cpp << "\n";
    }
    cpp << "};\n\n";

    /* 将每条规则的 actionCode 原样嵌入 switch；return -2 表示继续扫描 */
    cpp << "static int execute_action(int ruleId) {\n    switch(ruleId) {\n";
    for (const auto& rule : rules) {
        cpp << "        case " << rule.id << ": " << rule.actionCode << "\n";
        cpp << "            return -2;\n";
    }
    cpp << "        default: return 0;\n    }\n}\n\n";

    /* 输入由 set_input 注入，yylex 在 [input_ptr, input_end) 上滑动窗口匹配 */
    cpp << "static char* input_buffer = nullptr;\n";
    cpp << "static const char* input_ptr;\n";
    cpp << "static const char* input_end;\n\n";
    cpp << "void set_input(const char* str) {\n";
    cpp << "    if (input_buffer) delete[] input_buffer;\n";
    cpp << "    size_t len = strlen(str);\n";
    cpp << "    input_buffer = new char[len + 1];\n";
    cpp << "    memcpy(input_buffer, str, len + 1);\n";
    cpp << "    input_ptr = input_buffer;\n";
    cpp << "    input_end = input_buffer + len;\n";
    cpp << "    yylineno = 1;\n";
    cpp << "}\n\n";

    /* 探测空白规则 id，用于“已匹配非空白记号后不再延伸空白” */
    int whitespaceRuleId = -1;
    for (const auto& rule : rules) {
        if (rule.regexStr.find("[ \\t\\v\\n\\f\\r]") != string::npos ||
            rule.regexStr.find("[ \\t\\v\\n\\f]") != string::npos) {
            whitespaceRuleId = rule.id;
            break;
        }
    }
    if (whitespaceRuleId < 0) whitespaceRuleId = 98;

    /* yylex_emit_token：设置 yytext/yyleng，回退 input_ptr，执行动作 */
    cpp << "static const int WHITESPACE_RULE = " << whitespaceRuleId << ";\n";
    cpp << "static char yytext_buf[10240];\n\n";
    cpp << "static int yylex_emit_token(const char*& start, const char* accept_pos, int rule,\n";
    cpp << "                            int& state, int& last_rule, const char*& last_accept) {\n";
    cpp << "    const char* end = accept_pos;\n";
    cpp << "    if (start < input_buffer) start = input_buffer;\n";
    cpp << "    if (end > input_end) end = input_end;\n";
    cpp << "    if (end < start) end = start;\n";
    cpp << "    input_ptr = end;\n";
    cpp << "    yyleng = (int)(end - start);\n";
    cpp << "    if ((size_t)yyleng < sizeof(yytext_buf)) {\n";
    cpp << "        strncpy(yytext_buf, start, yyleng);\n";
    cpp << "        yytext_buf[yyleng] = '\\0';\n";
    cpp << "        yytext = yytext_buf;\n";
    cpp << "    } else {\n";
    cpp << "        static char* dyn_buf = nullptr;\n";
    cpp << "        delete[] dyn_buf;\n";
    cpp << "        dyn_buf = new char[yyleng + 1];\n";
    cpp << "        strncpy(dyn_buf, start, yyleng);\n";
    cpp << "        dyn_buf[yyleng] = '\\0';\n";
    cpp << "        yytext = dyn_buf;\n";
    cpp << "    }\n";
    cpp << "    start = input_ptr;\n";
    cpp << "    state = 0;\n";
    cpp << "    yylval.ival = 0;\n";
    cpp << "    yylval.sval = nullptr;\n";
    cpp << "    yylval.ptr = nullptr;\n";
    cpp << "    int ret = execute_action(rule);\n";
    cpp << "    last_rule = -1;\n";
    cpp << "    last_accept = nullptr;\n";
    cpp << "    return ret;\n";
    cpp << "}\n\n";

    /* 主扫描循环：无转移时若存在 last_accept 则发射记号，否则报错并跳过一字节 */
    cpp << "extern \"C\" int yylex() {\n";
    cpp << "    if (input_ptr < input_buffer) input_ptr = input_buffer;\n";
    cpp << "    if (input_ptr > input_end) input_ptr = input_end;\n";
    cpp << "    if (input_ptr >= input_end) return 0;\n";
    cpp << "    int state = 0;\n";
    cpp << "    const char* last_accept = nullptr;\n";
    cpp << "    int last_rule = -1;\n";
    cpp << "    const char* start = input_ptr;\n";
    cpp << "    while (1) {\n";
    cpp << "        if (input_ptr >= input_end) {\n";
    cpp << "            if (last_rule != -1) {\n";
    cpp << "                int ret = yylex_emit_token(start, last_accept, last_rule, state, last_rule, last_accept);\n";
    cpp << "                if (ret == -2) continue;\n";
    cpp << "                return ret;\n";
    cpp << "            }\n";
    cpp << "            return 0;\n";
    cpp << "        }\n";
    cpp << "        if (input_ptr < input_end && *input_ptr == '\\0') {\n";
    cpp << "            input_ptr++;\n";
    cpp << "            continue;\n";
    cpp << "        }\n";
    cpp << "        char ch = *input_ptr;\n";
    cpp << "        int nxt = nextState[state][(unsigned char)ch];\n";
    cpp << "        if (nxt == -1) {\n";
    cpp << "            if (last_rule != -1) {\n";
    cpp << "                int ret = yylex_emit_token(start, last_accept, last_rule, state, last_rule, last_accept);\n";
    cpp << "                if (ret == -2) continue;\n";
    cpp << "                return ret;\n";
    cpp << "            } else {\n";
    cpp << "                char bad = *input_ptr;\n";
    cpp << "                fprintf(stderr, \"Lexical error at line %d: illegal character '\", yylineno);\n";
    cpp << "                if (isprint((unsigned char)bad)) fprintf(stderr, \"%c\", bad);\n";
    cpp << "                else fprintf(stderr, \"\\\\x%02x\", (unsigned char)bad);\n";
    cpp << "                fprintf(stderr, \"'\\n\");\n";
    cpp << "                input_ptr++;\n";
    cpp << "                bump_yylineno(bad);\n";
    cpp << "                start = input_ptr;\n";
    cpp << "                state = 0;\n";
    cpp << "                last_accept = nullptr;\n";
    cpp << "                last_rule = -1;\n";
    cpp << "                continue;\n";
    cpp << "            }\n";
    cpp << "        } else {\n";
    cpp << "            state = nxt;\n";
    cpp << "            input_ptr++;\n";
    cpp << "            bump_yylineno(ch);\n";
    cpp << "            if (acceptInfo[state].accept) {\n";
    cpp << "                int rule = acceptInfo[state].ruleId;\n";
    cpp << "                if (rule == WHITESPACE_RULE && last_rule != -1 && last_rule != WHITESPACE_RULE) {\n";
    cpp << "                    int ret = yylex_emit_token(start, last_accept, last_rule, state, last_rule, last_accept);\n";
    cpp << "                    if (ret == -2) continue;\n";
    cpp << "                    return ret;\n";
    cpp << "                }\n";
    cpp << "                last_accept = input_ptr;\n";
    cpp << "                last_rule = rule;\n";
    cpp << "            }\n";
    cpp << "        }\n";
    cpp << "    }\n";
    cpp << "}\n\n";
    cpp << epilogue << "\n";  /* 用户 %% 段之后的附加 C 代码 */
}
